### ISSUE TITLE
Fix for kernel 6.17

### ISSUE THREAD

**Issue by stas-zozulja** [pulponair/rtl8852au#38]
First of all, I really appreciate your efforts on continuing the work on this driver.

I ran into a problem when trying to build on kernel 6.17, due to the changes in function signatures `set_wiphy_params`, `get_tx_power`, and `set_tx_power` the build was failing.
```
  CC [M]  os_dep/linux/ioctl_cfg80211.o
os_dep/linux/ioctl_cfg80211.c:9193:29: error: initialization of ‘int (*)(struct wiphy *, int,  u32)’ {aka ‘int (*)(struct wiphy *, int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct wiphy *, u32)’ {aka ‘int (*)(struct wiphy *, unsigned int)’} [-Wincompatible-pointer-types]
 9193 |         .set_wiphy_params = cfg80211_rtw_set_wiphy_params,
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9193:29: note: (near initialization for ‘rtw_cfg80211_ops.set_wiphy_params’)
os_dep/linux/ioctl_cfg80211.c:3275:12: note: ‘cfg80211_rtw_set_wiphy_params’ declared here
 3275 | static int cfg80211_rtw_set_wiphy_params(struct wiphy *wiphy, u32 changed)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9198:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, int,  enum nl80211_tx_power_setting,  int)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, enum nl80211_tx_power_setting,  int)’ [-Wincompatible-pointer-types]
 9198 |         .set_tx_power = cfg80211_rtw_set_txpower,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9198:25: note: (near initialization for ‘rtw_cfg80211_ops.set_tx_power’)
os_dep/linux/ioctl_cfg80211.c:4199:12: note: ‘cfg80211_rtw_set_txpower’ declared here
 4199 | static int cfg80211_rtw_set_txpower(struct wiphy *wiphy,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9199:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, int,  unsigned int,  int *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, unsigned int,  int *)’ [-Wincompatible-pointer-types]
 9199 |         .get_tx_power = cfg80211_rtw_get_txpower,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
os_dep/linux/ioctl_cfg80211.c:9199:25: note: (near initialization for ‘rtw_cfg80211_ops.get_tx_power’)
os_dep/linux/ioctl_cfg80211.c:4234:12: note: ‘cfg80211_rtw_get_txpower’ declared here
 4234 | static int cfg80211_rtw_get_txpower(struct wiphy *wiphy,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~
```

I was able to fix this and providing PR  https://github.com/pulponair/rtl8852au/pull/37 just in case if anyone else has the same issue.

P.S. As I don't have much experience in kernel development feel free to suggest any improvements or simply close if the issue has already been addressed.
Thank you!

**Comment by pulponair** [comment]
@stas-zozulja thank you very much. Merged :)
